// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAibHzqhdZgohuIZ3IU-8aiEtS_n0h859U',
    appId: '1:1020919356845:web:4bd0e3d165e222a8215524',
    messagingSenderId: '1020919356845',
    projectId: 'echo-trip-planner',
    authDomain: 'echo-trip-planner.firebaseapp.com',
    storageBucket: 'echo-trip-planner.firebasestorage.app',
    measurementId: 'G-P68MRSKBY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCnqpDbOb8cGrnYkFaPnSoJPEIk66eS4',
    appId: '1:1020919356845:android:a94acc14d511622a215524',
    messagingSenderId: '1020919356845',
    projectId: 'echo-trip-planner',
    storageBucket: 'echo-trip-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYs1DOMgktdIk5VJMdZzeP3hR7gFWUuA',
    appId: '1:1020919356845:ios:84e63227aa17cbd7215524',
    messagingSenderId: '1020919356845',
    projectId: 'echo-trip-planner',
    storageBucket: 'echo-trip-planner.firebasestorage.app',
    iosBundleId: 'com.example.echotripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYs1DOMgktdIk5VJMdZzeP3hR7gFWUuA',
    appId: '1:1020919356845:ios:84e63227aa17cbd7215524',
    messagingSenderId: '1020919356845',
    projectId: 'echo-trip-planner',
    storageBucket: 'echo-trip-planner.firebasestorage.app',
    iosBundleId: 'com.example.echotripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAibHzqhdZgohuIZ3IU-8aiEtS_n0h859U',
    appId: '1:1020919356845:web:4a4299ea7f79af96215524',
    messagingSenderId: '1020919356845',
    projectId: 'echo-trip-planner',
    authDomain: 'echo-trip-planner.firebaseapp.com',
    storageBucket: 'echo-trip-planner.firebasestorage.app',
    measurementId: 'G-NGPNR61KDF',
  );
}
